server:
  port: 8080

spring:
  datasource:
    #    url: jdbc:mysql://host.docker.internal:3306/ec?useSSL=false&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/ec?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000  # 最大等待時間，超過則拋錯
      pool-name: HikariPool

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect

#  redis:
#    host: localhost
#    port: 6379
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

mybatis:
  mapper-locations: classpath*:/mybatis/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
